name: Mon workflow Azure
on: [push]

env:
  AZURE_RESOURCE_GROUP: RG-IMPE  #set this to your resource group name 
  STORAGE_ACCOUNT: jonathan26407487773           #set this to your storage-account-name
  REGISTRY_NAME: myregistry_jonathan      #set this to your desired registry name
  CONTAINER_NAME: mycontainer_jonathan    #set this to your desired container name
  IMAGE_NAME: myimage_jonathan            #set this to the name of the image you want to use

jobs:
  mon-job-azure:
    runs-on: ubuntu-latest
    steps:
    - name: Se connecter à Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Créer un Azure Container Registry
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az acr create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.REGISTRY_NAME }} --sku Basic
    
    - name: Récupérer les informations d'identification du registre
      id: get_registry_credentials
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "::set-output name=login_server::$(az acr show --name ${{ env.REGISTRY_NAME }} --query loginServer --output tsv)"
          echo "::set-output name=username::$(az acr credential show --name ${{ env.REGISTRY_NAME }} --query username --output tsv)"
          echo "::set-output name=password::$(az acr credential show --name ${{ env.REGISTRY_NAME }} --query passwords[0].value --output tsv)"
    
    - name: Ajouter les clés à Secrets GitHub Action
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: REGISTRY_LOGIN_SERVER
        value: ${{ steps.get_registry_credentials.outputs.login_server }}
        token: ${{ secrets.MY_PAT }}
    
    - name: Ajouter les clés à Secrets GitHub Action
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: REGISTRY_USERNAME
        value: ${{ steps.get_registry_credentials.outputs.username }}
        token: ${{ secrets.MY_PAT }}
    
    - name: Ajouter les clés à Secrets GitHub Action
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: REGISTRY_PASSWORD
        value: ${{ steps.get_registry_credentials.outputs.password }}
        token: ${{ secrets.MY_PAT }}
    
    - name: Ajouter les clés à Secrets GitHub Action
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: RESOURCE_GROUP
        value: ${{ env.AZURE_RESOURCE_GROUP }}
        token: ${{ secrets.MY_PAT }}
    
    - name: Créer un conteneur Azure
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az container create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.CONTAINER_NAME }} \
            --image ${{ env.IMAGE_NAME }} \
            --dns-name-label ${{ env.CONTAINER_NAME }} \
            --ports 80
    
    # Ajoutez ici les étapes supplémentaires pour exécuter des commandes d'administration sur des ressources Azure
